remote_theme: pages-themes/hacker@v0.2.0
# https://github.com/pages-themes/hacker
# Other themes:https://pages.github.com/themes/
# https://github.com/pages-themes/architect
plugins:
- jekyll-remote-theme
title: Github Projects
logo: https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png
description: Test
