remote_theme: pages-themes/leap-day@v0.2.0
# https://github.com/pages-themes/leap-day
# Other themes:https://pages.github.com/themes/
# https://github.com/pages-themes/architect
# https://github.com/pages-themes/hacker
plugins:
- jekyll-remote-theme
title: Github Projects
logo: https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png
description: Test
show_downloads: false
github:
  zip_url: http://example.com/download.zip
  another_url: http://example.com/download_2.zip
